version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/python:3.8-buster

    steps:
      - checkout
      - run:
          name: "Validate JSON"
          command: python3 ./activities.py validate

